### ISSUE TITLE
cant use in node 16+

### ISSUE THREAD

**Issue by Doris0812** [capnproto/node-capnp#73]
node-gyp error

**Comment by Doris0812** [comment]
Does node capnp support running in the Electron environment? Why did I downgrade the node version to version 14+and place it in the Electron environment? The console reported an error of Uncaught (in promise) Error: Cannot find module 'capnp'

Requirement stack:

-Electron/js2c/renderer_ Init

**Comment by Doris0812** [comment]
Error: `capnp.node` is missing. Try reinstalling `node-capnp`?
    at Object.<anonymous> (D:\chrome下载\node-capnp-node14\node-capnp-node14\src\node-capnp\capnp.js:42:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\chrome\node-capnp-node14\node-capnp-node14\src\node-capnp\capnp-test.js:23:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
npm ERR! Test failed.  See above for more details.

**Comment by kentonv** [comment]
Unfortunately I don't really have time to bring node-capnp up to date.

It might be better to look at a pure-JavaScript capnp implementation, like: https://github.com/jdiaz5513/capnp-ts
